/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.12).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.RelationshipDescriptions;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-04-02T09:57:33.700Z")

@Api(value = "descriptions", description = "the descriptions API")
@RequestMapping(value = "/v1")
public interface DescriptionsApi {

    @ApiOperation(value = "Relationship descriptions", nickname = "descriptionsGet", notes = "Get the descriptions of each relationship", response = RelationshipDescriptions.class, tags={ "contacts", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "success", response = RelationshipDescriptions.class) })
    @RequestMapping(value = "/descriptions",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<RelationshipDescriptions> descriptionsGet() {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{  \"description\" : \"coworker - Some one you work with periodically. You both perform tasks for same employer or organization. Could be a manager or subordinate.\"}", RelationshipDescriptions.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default DescriptionsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
